# Generated by Django 5.0.1 on 2025-10-15 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_status_chatmessage_chatparticipant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Tổng giá dự án", max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="VND", max_length=3)),
                ("estimated_start_date", models.DateField(blank=True, null=True)),
                ("estimated_end_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_duration_days",
                    models.IntegerField(
                        blank=True, help_text="Số ngày ước tính", null=True
                    ),
                ),
                (
                    "milestones",
                    models.JSONField(
                        default=list, help_text="Các mốc thanh toán và deliverables"
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True, help_text="Điều khoản thanh toán", null=True
                    ),
                ),
                (
                    "scope_of_work",
                    models.TextField(
                        blank=True, help_text="Phạm vi công việc chi tiết", null=True
                    ),
                ),
                (
                    "deliverables",
                    models.JSONField(
                        default=list, help_text="Danh sách sản phẩm bàn giao"
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True, help_text="Điều khoản và điều kiện", null=True
                    ),
                ),
                (
                    "warranty_terms",
                    models.TextField(
                        blank=True, help_text="Điều khoản bảo hành", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản thảo"),
                            ("sent", "Đã gửi"),
                            ("viewed", "Đã xem"),
                            ("accepted", "Đã chấp nhận"),
                            ("rejected", "Từ chối"),
                            ("negotiating", "Đang thương thảo"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(
                        blank=True, help_text="Ghi chú từ khách hàng", null=True
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, help_text="Giá trị đến ngày", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal",
                "verbose_name_plural": "Proposals",
                "db_table": "proposals",
                "ordering": ["-created_at"],
            },
        ),
    ]
