# Generated by Django 5.0.1 on 2025-10-15 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_proposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=500000,
                help_text="Số tiền cọc tối thiểu 500,000 VND",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="deposit_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin duyệt cọc",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_deposits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="deposit_paid",
            field=models.BooleanField(default=False, help_text="Đã cọc chưa"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="deposit_paid_at",
            field=models.DateTimeField(
                blank=True, help_text="Thời gian cọc", null=True
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="phases",
            field=models.JSONField(
                default=list, help_text="Các giai đoạn thực hiện dự án"
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="project_analysis",
            field=models.TextField(
                blank=True, help_text="Chi tiết phân tích dự án từ Operis", null=True
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="team_members",
            field=models.JSONField(
                default=list, help_text="Danh sách nhân sự thực hiện"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="estimated_duration_days",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Số ngày ước tính (tự động tính từ các giai đoạn)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="milestones",
            field=models.JSONField(
                default=list, help_text="Các mốc thanh toán (deprecated - dùng phases)"
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tổng giá dự án (tự động tính từ các giai đoạn)",
                max_digits=12,
            ),
        ),
    ]
