# Generated by Django 5.0.1 on 2025-10-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0005_proposal_deposit_amount_proposal_deposit_approved_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="customer_approvals",
            field=models.JSONField(
                default=dict,
                help_text="Trạng thái đồng ý từng phần: {analysis: bool, deposit: bool, phases: bool, team: bool, commitments: bool}",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("negotiation", "Đang thương thảo"),
                    ("deposit", "Chờ đặt cọc"),
                    ("pending", "Chờ xử lý"),
                    ("in_progress", "Đang thực hiện"),
                    ("on_hold", "Tạm dừng"),
                    ("completed", "Hoàn thành"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
