# Generated by Django 5.0.1 on 2025-10-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_proposal_customer_approvals_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="payment_proof",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Thông tin chứng từ thanh toán (transaction_id, screenshot_url, etc.) - Dành cho tích hợp SePay",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="payment_submitted",
            field=models.BooleanField(
                default=False,
                help_text="Khách hàng đã submit thanh toán (chờ xác nhận)",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="payment_submitted_at",
            field=models.DateTimeField(
                blank=True, help_text="Thời gian khách submit thanh toán", null=True
            ),
        ),
    ]
