# Generated by Django 5.0.1 on 2025-10-16 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_add_phase_payment_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 stars"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ],
                        help_text="Project rating from 1 to 5 stars",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(help_text="General feedback about the project"),
                ),
                (
                    "complaint",
                    models.TextField(
                        blank=True, help_text="Customer complaints if any", null=True
                    ),
                ),
                (
                    "feature_request",
                    models.TextField(
                        blank=True,
                        help_text="Additional features customer wants",
                        null=True,
                    ),
                ),
                (
                    "upgrade_request",
                    models.TextField(
                        blank=True,
                        help_text="System upgrade or maintenance requests",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_response",
                    models.TextField(
                        blank=True,
                        help_text="Admin/Sales response to feedback",
                        null=True,
                    ),
                ),
                ("admin_responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="projects.project",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Feedback",
                "verbose_name_plural": "Project Feedbacks",
                "db_table": "project_feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
