# Generated by Django 5.0.1 on 2025-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_projectfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfeedback",
            name="acceptance_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected - Needs Revision"),
                ],
                default="pending",
                help_text="Acceptance decision: accept or request changes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectfeedback",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="When customer accepted the project", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectfeedback",
            name="rejected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When customer rejected (requested revisions)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectfeedback",
            name="revision_completed",
            field=models.BooleanField(
                default=False, help_text="Has the requested revision been completed"
            ),
        ),
        migrations.AddField(
            model_name="projectfeedback",
            name="revision_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectfeedback",
            name="revision_details",
            field=models.TextField(
                blank=True,
                help_text="Detailed list of changes/fixes required",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("negotiation", "Đang thương thảo"),
                    ("deposit", "Chờ đặt cọc"),
                    ("pending", "Chờ xử lý"),
                    ("in_progress", "Đang thực hiện"),
                    ("on_hold", "Tạm dừng"),
                    ("pending_acceptance", "Chờ nghiệm thu"),
                    ("revision_required", "Yêu cầu sửa chữa"),
                    ("completed", "Hoàn thành"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectfeedback",
            name="admin_response",
            field=models.TextField(
                blank=True,
                help_text="Admin/Sales response to feedback or revision completion",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectfeedback",
            name="complaint",
            field=models.TextField(
                blank=True,
                help_text="Issues or problems that need to be fixed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectfeedback",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 stars"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ],
                help_text="Project rating from 1 to 5 stars",
                null=True,
            ),
        ),
    ]
