# Generated by Django 5.0.1 on 2025-10-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="full_payment_option",
            field=models.BooleanField(
                default=False,
                help_text="Khách hàng chọn thanh toán toàn bộ (1 lần) thay vì từng giai đoạn",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="full_payment_paid",
            field=models.BooleanField(default=False, help_text="Đã thanh toán toàn bộ"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="full_payment_paid_at",
            field=models.DateTimeField(
                blank=True, help_text="Thời gian thanh toán toàn bộ", null=True
            ),
        ),
    ]
