# Generated by Django 5.0.1 on 2025-10-20 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_add_full_payment_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Tên dự án mẫu, ví dụ: 'Xây dựng hệ thống quản trị doanh nghiệp'",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(help_text="Mô tả chi tiết về dự án")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web_development", "Phát triển Website"),
                            ("mobile_app", "Ứng dụng Mobile"),
                            ("enterprise_system", "Hệ thống Doanh nghiệp"),
                            ("ecommerce", "Thương mại điện tử"),
                            ("crm_system", "Hệ thống CRM"),
                            ("erp_system", "Hệ thống ERP"),
                            ("ai_ml", "AI & Machine Learning"),
                            ("consulting", "Tư vấn"),
                            ("maintenance", "Bảo trì & Hỗ trợ"),
                        ],
                        default="web_development",
                        help_text="Danh mục dự án",
                        max_length=50,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class hoặc emoji cho template, ví dụ: 🏢",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "price_min",
                    models.DecimalField(
                        decimal_places=0, help_text="Giá tối thiểu (VNĐ)", max_digits=12
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Giá tối đa (VNĐ), để trống nếu muốn hiển thị 'Liên hệ'",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "estimated_duration_min",
                    models.IntegerField(
                        help_text="Thời gian thực hiện tối thiểu (ngày)"
                    ),
                ),
                (
                    "estimated_duration_max",
                    models.IntegerField(
                        blank=True,
                        help_text="Thời gian thực hiện tối đa (ngày)",
                        null=True,
                    ),
                ),
                (
                    "key_features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Danh sách tính năng chính (array of strings)",
                    ),
                ),
                (
                    "deliverables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sản phẩm bàn giao (array of strings)",
                    ),
                ),
                (
                    "technologies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Công nghệ sử dụng (array of strings)",
                    ),
                ),
                (
                    "phases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Các giai đoạn thực hiện (array of objects):\n        [\n            {\n                "name": "Phân tích & Thiết kế",\n                "duration_days": 7,\n                "percentage": 20,\n                "description": "..."\n            },\n            ...\n        ]\n        ',
                    ),
                ),
                (
                    "team_structure",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Cấu trúc team dự kiến (object):\n        {\n            "project_manager": 1,\n            "developers": 2,\n            "designers": 1,\n            "testers": 1\n        }\n        ',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Template có đang hoạt động không (hiển thị cho customer)",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Thứ tự hiển thị (số càng nhỏ càng ưu tiên)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Template",
                "verbose_name_plural": "Project Templates",
                "db_table": "project_templates",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
