# Generated by Django 5.0.1 on 2025-10-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_projecttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttemplate",
            name="options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Cấu hình options động cho dự án (array of option objects):\n        [\n            {\n                "id": "language",\n                "type": "single_select",\n                "label": "Ngôn ngữ",\n                "description": "Chọn ngôn ngữ cho website",\n                "required": true,\n                "choices": [\n                    {"value": "vi", "label": "Tiếng Việt", "price_modifier": 0},\n                    {"value": "en", "label": "Tiếng Anh", "price_modifier": 3000000},\n                    {"value": "multi", "label": "Đa ngôn ngữ", "price_modifier": 8000000}\n                ]\n            },\n            {\n                "id": "features",\n                "type": "multi_select",\n                "label": "Tính năng bổ sung",\n                "description": "Chọn các tính năng muốn thêm",\n                "required": false,\n                "choices": [\n                    {"value": "seo", "label": "SEO Nâng cao", "price_modifier": 5000000},\n                    {"value": "analytics", "label": "Google Analytics", "price_modifier": 2000000},\n                    {"value": "chat", "label": "Live Chat", "price_modifier": 3000000}\n                ]\n            },\n            {\n                "id": "package",\n                "type": "package",\n                "label": "Gói dịch vụ",\n                "description": "Chọn gói phù hợp với nhu cầu",\n                "required": true,\n                "choices": [\n                    {\n                        "value": "basic",\n                        "label": "Basic",\n                        "price": 30000000,\n                        "duration_days": 30,\n                        "features": ["5 trang", "Responsive", "SEO cơ bản"]\n                    },\n                    {\n                        "value": "standard",\n                        "label": "Standard",\n                        "price": 50000000,\n                        "duration_days": 45,\n                        "features": ["10 trang", "Responsive", "SEO nâng cao", "Admin panel"]\n                    }\n                ]\n            },\n            {\n                "id": "product_count",\n                "type": "number_range",\n                "label": "Số lượng sản phẩm",\n                "description": "Số sản phẩm tối đa trên hệ thống",\n                "required": true,\n                "min": 100,\n                "max": 10000,\n                "step": 100,\n                "default": 500,\n                "price_per_unit": 1000\n            },\n            {\n                "id": "custom_note",\n                "type": "text_input",\n                "label": "Yêu cầu đặc biệt",\n                "description": "Nhập yêu cầu tùy chỉnh của bạn",\n                "required": false,\n                "placeholder": "Ví dụ: Tích hợp với hệ thống ERP hiện có..."\n            }\n        ]\n        ',
            ),
        ),
    ]
