# Generated by Django 5.0.1 on 2025-10-15 05:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web_development", "Web Development"),
                            ("mobile_app", "Mobile App Development"),
                            ("ui_ux_design", "UI/UX Design"),
                            ("ecommerce", "E-commerce Solution"),
                            ("crm_system", "CRM System"),
                            ("erp_system", "ERP System"),
                            ("ai_ml", "AI/ML Solutions"),
                            ("consulting", "IT Consulting"),
                            ("maintenance", "Maintenance & Support"),
                        ],
                        default="web_development",
                        max_length=50,
                    ),
                ),
                ("short_description", models.TextField()),
                ("full_description", models.TextField()),
                ("key_features", models.JSONField(default=list)),
                ("differentiators", models.JSONField(default=list)),
                ("process_stages", models.JSONField(default=list)),
                ("team_structure", models.JSONField(default=dict)),
                ("estimated_team_size", models.IntegerField(default=1)),
                (
                    "estimated_duration_min",
                    models.IntegerField(help_text="Thời gian tối thiểu (ngày)"),
                ),
                (
                    "estimated_duration_max",
                    models.IntegerField(help_text="Thời gian tối đa (ngày)"),
                ),
                (
                    "price_range_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_range_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("icon", models.CharField(default="briefcase", max_length=50)),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("gallery", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("technologies", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "services",
                "ordering": ["order", "-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("project_description", models.TextField()),
                ("requirements", models.JSONField(default=dict)),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "expected_timeline",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Reviewing"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("converted", "Converted to Project"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "converted_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_service_request",
                        to="projects.project",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
                "db_table": "service_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
