# Generated by Django 5.0.1 on 2025-10-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="required_functions",
            field=models.JSONField(
                default=list, help_text="Danh sách chức năng cần có"
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="special_requirements",
            field=models.TextField(blank=True, help_text="Yêu cầu đặc biệt", null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="system_users_count",
            field=models.IntegerField(
                default=1, help_text="Số lượng người sử dụng hệ thống"
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="workflow_description",
            field=models.TextField(
                blank=True, help_text="Mô tả luồng công việc", null=True
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="zalo_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="project_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
