# Generated by Django 5.0.1 on 2025-10-21 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("facebook", "Facebook"),
                            ("github", "GitHub"),
                        ],
                        help_text="OAuth provider name (google, facebook, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(
                        help_text="Unique user ID from the provider", max_length=255
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="OAuth access token (encrypted in production)"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="OAuth refresh token (encrypted in production)",
                        null=True,
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the access token expires", null=True
                    ),
                ),
                (
                    "profile_data",
                    models.JSONField(
                        default=dict, help_text="Cached user profile data from provider"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email from provider (for matching)", max_length=254
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the primary login method"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this social account was used to login",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with this social account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Account",
                "verbose_name_plural": "Social Accounts",
                "db_table": "social_accounts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "provider"],
                        name="social_acco_user_id_e2981d_idx",
                    ),
                    models.Index(
                        fields=["provider", "provider_user_id"],
                        name="social_acco_provide_7847d7_idx",
                    ),
                    models.Index(fields=["email"], name="social_acco_email_2e8666_idx"),
                ],
                "unique_together": {("provider", "provider_user_id")},
            },
        ),
    ]
